# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bujo < Formula
  desc "A command-line Bullet Journal with AI-powered summaries"
  homepage "https://github.com/typingincolor/bujo"
  version "0.0.0-nightly.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/typingincolor/bujo/releases/download/v0.0.0-nightly.18/bujo_0.0.0-nightly.18_darwin_amd64.tar.gz"
      sha256 "bb607be381806a392c62043d54b2f3c1b2546feba8ad06a32d7e92312823938b"

      def install
        bin.install "bujo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/typingincolor/bujo/releases/download/v0.0.0-nightly.18/bujo_0.0.0-nightly.18_darwin_arm64.tar.gz"
      sha256 "80be33f44e880905548c166ecdd83064d25b09749b4404ffdd007c8dc85a74db"

      def install
        bin.install "bujo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typingincolor/bujo/releases/download/v0.0.0-nightly.18/bujo_0.0.0-nightly.18_linux_amd64.tar.gz"
      sha256 "9f3e26b2dbcb7f1d6455eef16487cea75c5422c261e5d6b2eb93adcd6d7d2829"
      def install
        bin.install "bujo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typingincolor/bujo/releases/download/v0.0.0-nightly.18/bujo_0.0.0-nightly.18_linux_arm64.tar.gz"
      sha256 "49c6342e2901f70bdd2f0006ad246d5529c60123aafb0f29e755fe331cd40642"
      def install
        bin.install "bujo"
      end
    end
  end

  def post_install
    (zsh_completion/"_bujo").write `#{bin}/bujo completion zsh`
  end

  def caveats
    <<~EOS
      For local AI, install and run Ollama:
        brew install ollama
        ollama pull llama3.2:1b

      For cloud AI, set GEMINI_API_KEY instead.
    EOS
  end

  test do
    system "#{bin}/bujo", "version"
  end
end
